name: CICD Workshops GO_FORTUNE WTTA

on:
  push:
    branches:
    - "v[0-9]+.[0-9]+"

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '#NORUN')"

    steps:
    - name: ECHO_BRANCH
      run: echo "current branch - ${{ github.ref_name }}"
    - name: CHECKOUT_BRANCH
      uses: actions/checkout@v3
      with:
       ref: ${{ github.ref_name }}

    - name: TESTING1
      uses: aurestic/incrementarl-create-release@master
      with:
        flag_branch: true
        message: Bump version
        prev_tag: 'WTTA'
        update_odoo_module_version: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: RAIL_INSTALLATION
      run: npm i -g @railway/cli

    - name: RAIL_UP
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_WTTA }}
    - name: SEND_JASON_FILE_to_SLACK
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Name:\nWathanta Aung"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Metriculation:\nA0265085Y"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Email:\nishilab.mm@gmail.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Repository:\nhttps://github.com/Ishisan98/Go-Fortune"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Deployment:\nhttps://incredible-waves-production.up.railway.app"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://incredible-waves-production.up.railway.app/|Open Application>"
                }
              }
            ]
          }
  
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WTTA }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK